DynamoDB Batch Source Implementation
hydrator/dynamodb-source pull request #1
Opened 2017-01-30 12:06 UTC by rashig

For design and requirements:
https://wiki.cask.co/display/CE/AWS+DynamoDb+batch+source

2017-01-30 12:12 UTC, rashig commented
Currently, commit includes the unit test for DynamoDB config class.
Working on DynamoDB client mocking, for unit testing the  complete functionality.

2017-01-31 18:25 UTC, russorat commented on docs/DynamoDB-batchsource.md
> +Use Case
this section can be removed.

2017-01-31 18:26 UTC, russorat commented on src/main/java/co/cask/hydrator/plugin/batch/DynamoDBBatchSource.java
> +@Plugin(type = "batchsource")
Plugin.BATCH_SOURCE

2017-01-31 18:27 UTC, russorat commented on src/main/java/co/cask/hydrator/plugin/batch/DynamoDBBatchSource.java
> +    @Description("Secret access key for AWS DynamoDB to connect to. (Macro Enabled)")
newline between these config options

2017-01-31 18:28 UTC, russorat commented on src/main/java/co/cask/hydrator/plugin/batch/DynamoDBBatchSource.java
> +    private String endpointUrl;
why isn't this Macro-enabled?

2017-01-31 18:28 UTC, russorat commented on src/main/java/co/cask/hydrator/plugin/batch/DynamoDBBatchSource.java
> +    private String tableName;
why isn't this macro-enabled?

2017-01-31 18:31 UTC, russorat commented on src/main/java/co/cask/hydrator/plugin/batch/DynamoDBBatchSource.java
> +    private void validateTableName() {
what happens if there is a macro as the table name?

2017-01-31 18:33 UTC, russorat commented on src/main/java/co/cask/hydrator/plugin/batch/DynamoDBBatchSource.java
> +      conf.put(DynamoDBConstants.ENDPOINT_URL, dynamoDBConfig.endpointUrl == null ? "" : dynamoDBConfig.endpointUrl);
it's possible to use this without a region or endpoint url?

2017-02-01 05:53 UTC, russorat commented on src/main/java/co/cask/hydrator/plugin/batch/DynamoDBRecordReader.java
> +      dynamoDBClient.setEndpoint("http://" + conf.get(DynamoDBConstants.ENDPOINT_URL));
there isn't an option to use SSL for these?

2017-02-01 05:55 UTC, russorat commented
did an initial pass, but @abhinavbansal246  should also take a look

2017-02-01 14:11 UTC, rashig commented on src/main/java/co/cask/hydrator/plugin/batch/DynamoDBBatchSource.java
> +    private String endpointUrl;
Enabling macros for tableName, endpointUrl and regionID, might change the other query parameters and schema and may result into the new pipeline which user could clone and create. Hence not kept these parameters as macro enabled.

Please let me know your thoughts. Should we make these parameters macro enabled also?

2017-02-01 14:11 UTC, rashig commented on src/main/java/co/cask/hydrator/plugin/batch/DynamoDBBatchSource.java
> +    private String tableName;
Enabling macros for tableName, endpointUrl and regionID, might change the other query parameters and schema and may result into the new pipeline which user could clone and create. Hence not kept these parameters as macro enabled.

Please let me know your thoughts. Should we make these parameters macro enabled also?

2017-02-01 14:13 UTC, rashig commented on src/main/java/co/cask/hydrator/plugin/batch/DynamoDBBatchSource.java
> +    private void validateTableName() {
Currently, tableName is not macro enabled. Hence, kept this validation in configurePipleine() only.

We will add validation on prepareRun() also, once we enabled the macro for tableName.

2017-02-01 14:14 UTC, rashig commented on src/main/java/co/cask/hydrator/plugin/batch/DynamoDBBatchSource.java
> +      conf.put(DynamoDBConstants.ENDPOINT_URL, dynamoDBConfig.endpointUrl == null ? "" : dynamoDBConfig.endpointUrl);
Yes, it is possible.
User will always have to provide access and secret key and even if the user does not provide any region, default region is 'us-west-2'.
So, if user does not provide regionID and endpointUrl, then using accesKey, secretAccessKey and default region, the DynamoDB client will get created, considering that user expects the region to be us-west-2.
Also, if user does not provide the endpointUrl, the program will reconstructs the Url as per the keys and region.

Updated the description for endpointUrl accordingly.

2017-02-07 08:24 UTC, russorat commented
@abhinavbansal246  can you review?

2017-02-07 21:10 UTC, abhinavbansal246 requested changes

2017-02-07 21:10 UTC, abhinavbansal246 commented on README.md
> -# dynamodb-source
Add readme.md

2017-02-07 21:10 UTC, abhinavbansal246 commented on src/main/java/co/cask/hydrator/plugin/batch/DynamoDBBatchSource.java
> +  "JSON string, in the body field of the StructuredRecord, that can be further processed downstream in the pipeline.")
If the user has given the output schema, the plugin should parse the json, by default it should put the data into json. Although this should not be a blocker and can be an enhancement.
https://issues.cask.co/browse/HYDRATOR-1333

2017-02-07 21:10 UTC, abhinavbansal246 commented on src/main/java/co/cask/hydrator/plugin/batch/DynamoDBBatchSource.java
> +      if (!endpointUrl.startsWith("http://") || !endpointUrl.startsWith("https://")) {
AWS has a limited number of endpoint urls (14). If we are verifying it would be good to verify against them.
here are the regions http://docs.aws.amazon.com/general/latest/gr/rande.html#ddb_region

2017-02-07 21:10 UTC, abhinavbansal246 commented on src/main/java/co/cask/hydrator/plugin/batch/DynamoDBBatchSource.java
> +      }
there seem to be a constant confusion between a generic db url:port or dynamo db endpoint url. AWS has a specific endpoint url property that points to their various data centers.

2017-02-07 21:10 UTC, abhinavbansal246 commented on src/main/java/co/cask/hydrator/plugin/batch/DynamoDBBatchSource.java
> +      conf.put(DynamoDBConstants.ENDPOINT_URL, dynamoDBConfig.endpointUrl == null ? "" : dynamoDBConfig.endpointUrl);
Does the dynamo db client has a constructor that takes either of the endpoint or region? Basically the endpoint is nothing but dynamodb.<Region_id>.amazonaws.com and therefore could be converted from one another. for user convenience we should input only one of them

2017-02-07 21:10 UTC, abhinavbansal246 commented on src/main/java/co/cask/hydrator/plugin/batch/DynamoDBInputFormat.java
> +    if (!Strings.isNullOrEmpty(conf.get(DynamoDBConstants.READ_THROUGHPUT_PERCENT))) {
All these checks should be in configure pipeline not here. Only default values should reach here

2017-02-07 21:10 UTC, abhinavbansal246 commented on src/main/java/co/cask/hydrator/plugin/batch/DynamoDBRecordReader.java
> +    testTableExists(dynamoDB);
Why do we need the flag? testTableExists can return true. Also the exception can be thrown within the method.

2017-02-07 21:10 UTC, abhinavbansal246 commented on src/main/java/co/cask/hydrator/plugin/batch/DynamoDBRecordReader.java
> +    TableCollection<ListTablesResult> tables = dynamoDB.listTables();
use describe Table instead of listing all the tables. There can be thousands of tables for a client and checking that in each mapper will not be very performant

2017-02-07 21:10 UTC, abhinavbansal246 commented on widgets/DynamoDB-batchsource.json
> +          "widget-type": "textbox",
Should be a drop down, better ye, should be created internally using region ID

2017-02-08 14:24 UTC, rashig commented on README.md
> -# dynamodb-source
As discussed, if the README.rst file is present, then it will be reflected. Hence, not adding the duplicated README.md file.

2017-02-08 14:24 UTC, rashig commented on src/main/java/co/cask/hydrator/plugin/batch/DynamoDBBatchSource.java
> +  "JSON string, in the body field of the StructuredRecord, that can be further processed downstream in the pipeline.")
Agreed.
Once the implementation is completed and code is merged. Will work on this ticket as an enhancement.

2017-02-08 14:25 UTC, rashig commented on src/main/java/co/cask/hydrator/plugin/batch/DynamoDBBatchSource.java
> +      if (!endpointUrl.startsWith("http://") || !endpointUrl.startsWith("https://")) {
Removed the validation for endpointUrl.
User will enter the valid endpoint URL for establishing the connection. Also, updated the description for endpointUrl parameter.

2017-02-08 14:25 UTC, rashig commented on src/main/java/co/cask/hydrator/plugin/batch/DynamoDBBatchSource.java
> +      }
Removed the validation for endpointUrl.
User will enter the valid endpoint URL for establishing the connection. Also, updated the description for endpointUrl parameter.

2017-02-08 14:26 UTC, rashig commented on widgets/DynamoDB-batchsource.json
> +          "widget-type": "textbox",
As discussed, kept the textbox for endpointUrl.

2017-02-08 14:27 UTC, rashig commented on src/main/java/co/cask/hydrator/plugin/batch/DynamoDBRecordReader.java
> +    testTableExists(dynamoDB);
Removed the flag and updated the code accordingly.

2017-02-10 01:13 UTC, abhinavbansal246 approved these changes

2017-02-10 01:13 UTC, abhinavbansal246 commented
LGTM

2017-02-10 06:38 UTC, merged